package forms;

import classes.Client;
import dataBase.Connexion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class AddClient extends javax.swing.JFrame {

    private Connexion db;
    /**
     * Creates new form AddClient
     */
    public AddClient() throws ClassNotFoundException {
        initComponents();
        db = new Connexion();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        cli_tel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cli_nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cli_prenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cli_courriel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cli_sexe = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cli_code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cli_nip = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Formulaire Ajout Client");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 60, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 310, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 10, 420));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 10, 420));

        cli_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_telActionPerformed(evt);
            }
        });
        jPanel1.add(cli_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Téléphone :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nom :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));
        jPanel1.add(cli_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 200, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Prenom :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));
        jPanel1.add(cli_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 200, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Courriel :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        cli_courriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_courrielActionPerformed(evt);
            }
        });
        jPanel1.add(cli_courriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 200, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Sexe :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 30));

        cli_sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(cli_sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 30));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 410, 80, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Code :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 30));

        cli_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_codeActionPerformed(evt);
            }
        });
        jPanel1.add(cli_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 200, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Nip :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 30));
        jPanel1.add(cli_nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cli_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cli_telActionPerformed

    private void cli_courrielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_courrielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cli_courrielActionPerformed

    private void cli_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cli_codeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        var prenom = cli_prenom.getText();
        var nom = cli_nom.getText();
        var courriel = cli_courriel.getText();
        var tel = cli_tel.getText();
        var sexe = cli_sexe.getSelectedItem().toString();
        var code = cli_code.getText();
        var nip = cli_nip.getText();
        
        String regex = "^[0-9]+$";
        
        
        if(prenom.isEmpty() || nom.isEmpty() || courriel.isEmpty() || tel.isEmpty() || sexe.isEmpty() || code.isEmpty() || nip.isEmpty()){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "Ajout", JOptionPane.ERROR_MESSAGE);
        }else{
            if(tel.matches(regex)){
                if(nip.matches(regex)){
                   if(nip.length() == 4){
                       if(!db.codeAlreadyUse(code)){
                           Client cli = new Client(code,Integer.parseInt(nip),nom, prenom, tel, courriel, sexe,0);
                           if(db.addClient(cli)){
                               JOptionPane.showMessageDialog(null, "Client ajouté avec succès");
                               this.dispose();
                           }else{
                              JOptionPane.showMessageDialog(null, "Erreur d'ajout client", "Ajout", JOptionPane.ERROR_MESSAGE); 
                           }
                       }else{
                           JOptionPane.showMessageDialog(null, "Le code existe déjà", "Ajout", JOptionPane.ERROR_MESSAGE);
                       }
                    }else{
                        JOptionPane.showMessageDialog(null, "La taille de NIP est de 4 chiffres", "Ajout", JOptionPane.ERROR_MESSAGE);
                    } 
                }else{
                    JOptionPane.showMessageDialog(null, "NIP doit avoir uniquement des chiffres", "Ajout", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Téléphone doit avoir uniquement des chiffres", "Ajout", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddClient().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cli_code;
    private javax.swing.JTextField cli_courriel;
    private javax.swing.JPasswordField cli_nip;
    private javax.swing.JTextField cli_nom;
    private javax.swing.JTextField cli_prenom;
    private javax.swing.JComboBox<String> cli_sexe;
    private javax.swing.JTextField cli_tel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
