/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import classes.Compte;
import dataBase.Connexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddCompte extends javax.swing.JFrame {

    private Connexion db;
    /**
     * Creates new form AddClient
     */
    public AddCompte() throws ClassNotFoundException {
        initComponents();
        db = new Connexion();
        CodeClient();
    }
    
    private void CodeClient(){
        cpt_code.removeAll();
        
        ResultSet rs = db.clients();
        
        try {
            while(rs.next()){
                cpt_code.addItem(rs.getString("code"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddCompte.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        cpt_solde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cpt_code = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cpt_etat = new javax.swing.JComboBox<>();
        cpte_type = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Formulaire Ajout Client");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 60, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 320, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 10, 330));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 330));

        cpt_solde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpt_soldeActionPerformed(evt);
            }
        });
        jPanel1.add(cpt_solde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 190, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Solde :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Type :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Etat :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));

        jPanel1.add(cpt_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, 30));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 80, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Code Client:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        cpt_etat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actif", "Desactif" }));
        jPanel1.add(cpt_etat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 190, 30));

        cpte_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compte Cheque", "Compte Hypothecaire", "Marge Credit", "Compte Epargne" }));
        jPanel1.add(cpte_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        var code = cpt_code.getSelectedItem().toString();
        var solde = cpt_solde.getText();
        var etat = "Actif".equals(cpt_etat.getSelectedItem().toString()) ? 1 : 0;
        var type = cpte_type.getSelectedItem().toString();
        ResultSet rs = null;
        ResultSet rsMarge = null;
        String regex = "^[0-9]+$";
        
        boolean legal = true;
        
        if(solde.isEmpty()){
            JOptionPane.showMessageDialog(null, "Veuillez renseigner tous les champs", "Ajout", JOptionPane.ERROR_MESSAGE);
        }else{
            if(solde.matches(regex)){
                Compte cpt = new Compte(Float.parseFloat(solde), etat, code, type, new Date());
                if(!type.equals("Compte Cheque")){
                    rs = db.getCompteByType("Compte Cheque", code);
                    rsMarge = db.getCompteByType("Marge Credit", code);
                    try {
                        if(rs.next()){
                            if(rsMarge.next()){
                                legal = false;
                                JOptionPane.showMessageDialog(null, "Le client a déjà une Marge de Crédit");
                            }
                        }else{                        
                            JOptionPane.showMessageDialog(null, "Le client n'a pas de Compte Chéque", "Ajout", JOptionPane.ERROR_MESSAGE);
                            legal = false;
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(AddCompte.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                if(legal){
                    if(db.addCompte(cpt)){
                        JOptionPane.showMessageDialog(null, "Compte ajouté avec succès");
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Erreur d'ajout", "Ajout", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Veuillez entrer un montant positif", "Ajout", JOptionPane.ERROR_MESSAGE);
            }           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cpt_soldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpt_soldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpt_soldeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddCompte().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddCompte.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cpt_code;
    private javax.swing.JComboBox<String> cpt_etat;
    private javax.swing.JTextField cpt_solde;
    private javax.swing.JComboBox<String> cpte_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
