
package dashboards;

import classes.Client;
import classes.Config;
import com.lampfallDev.Main;
import dataBase.Connexion;
import forms.FormDepot;
import forms.FormPaiementFacture;
import forms.FormRetrait;
import forms.FormTransfert;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ClientDashboard extends javax.swing.JFrame {
    private Connexion db;
    private Client client;
    /**
     * Creates new form ClientDashboard
     */
    public ClientDashboard() throws ClassNotFoundException {
        initComponents();
         new Config(this);
         DateFormat df = new SimpleDateFormat("dd/MM/YYYY à H:mm");
         loginDate.setText(df.format(new Date()));
        body.setSelectedIndex(0);
        setSubHeader(sOpt);
        this.db = new Connexion();
        sProfile.setVisible(false);
        
    }
    
    public ClientDashboard(Client client) throws ClassNotFoundException{
        this();
        this.client = client;
        client_name.setText(this.client.getCode());
        getComptes();
        chargerTableOperation();
 
        this.resultat.setVisible(false);
    }

    private void getComptes(){
        ResultSet rs = db.getCompteByCode(client.getCode());
        try {
            while(rs.next()){
                numCpt.addItem(rs.getString("numCpt"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormDepot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void removeActive(JLabel label){
        label.setOpaque(false);
        label.setBackground(new Color(255,255,255));
    }
    
    private void setActive(JLabel label, int index){
        label.setOpaque(true);
        label.setBackground(new Color(0,102,204));
        body.setSelectedIndex(index);
        setSubHeader(label);
    }
    
    private void setSubHeader(JLabel label){
        subHeaderTitle.setText(label.getText());
        subHeaderTitle.setIcon(label.getIcon());
    }
    
    private void chargerTableOperation(){
        tabOperation.removeAll();
        
        DefaultTableModel dtm = new DefaultTableModel();
         DateFormat df = new  SimpleDateFormat("dd/MM/YYYY");
        
        String entete []={"N°Opération","N° Compte", "Type", "Montant", "Date"}; 
        for (int i = 0; i < entete.length; i++) {
            dtm.addColumn(entete[i]);
        }
        
        ResultSet rs = db.operationsClient(this.client.getCode());
        
        try {
            while(rs.next()){
                String entrees [] = {rs.getString("numOpt"), rs.getString("numCpt"), rs.getString("typeOpt"), rs.getFloat("montant")+" $", df.format(rs.getDate("date"))};
                dtm.addRow(entrees);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        tabOperation.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sOpt = new javax.swing.JLabel();
        sProfile = new javax.swing.JLabel();
        sCompte = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        client_name = new javax.swing.JLabel();
        loginDate = new javax.swing.JLabel();
        subHeader = new javax.swing.JPanel();
        subHeaderTitle = new javax.swing.JLabel();
        body = new javax.swing.JTabbedPane();
        bOpt = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabOperation = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        bCompte = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numCpt = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        resultat = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        r_solde = new javax.swing.JLabel();
        r_compte = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        r_type = new javax.swing.JLabel();
        bProfile = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 51, 153));
        sidebar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lg.png"))); // NOI18N
        sidebar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        sOpt.setBackground(new java.awt.Color(0, 102, 204));
        sOpt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sOpt.setForeground(new java.awt.Color(255, 255, 255));
        sOpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction.png"))); // NOI18N
        sOpt.setText("Opérations");
        sOpt.setOpaque(true);
        sOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sOptMouseClicked(evt);
            }
        });
        sidebar.add(sOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        sProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sProfile.setForeground(new java.awt.Color(255, 255, 255));
        sProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profil.png"))); // NOI18N
        sProfile.setText("Mon Profil");
        sProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sProfileMouseClicked(evt);
            }
        });
        sidebar.add(sProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 40));

        sCompte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sCompte.setForeground(new java.awt.Color(255, 255, 255));
        sCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/compte.png"))); // NOI18N
        sCompte.setText("Compte");
        sCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sCompteMouseClicked(evt);
            }
        });
        sidebar.add(sCompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        jPanel1.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 520));

        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        client_name.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        client_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_name.png"))); // NOI18N
        client_name.setText("client");
        header.add(client_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 50));

        loginDate.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        loginDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginDate.setText("jLabel2");
        header.add(loginDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, 270, 30));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 760, 50));

        subHeader.setBackground(new java.awt.Color(0, 51, 153));
        subHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subHeaderTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        subHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        subHeader.add(subHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, 40));

        jPanel1.add(subHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 770, 40));

        bOpt.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Faire un Retrait");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Faire un Dépôt");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Paiement Facture");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 0, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Faire un Transfert");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabOperation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabOperation);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Liste des dernières opérations");

        jButton5.setBackground(new java.awt.Color(51, 0, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        jButton5.setText("Actualiser");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bOptLayout = new javax.swing.GroupLayout(bOpt);
        bOpt.setLayout(bOptLayout);
        bOptLayout.setHorizontalGroup(
            bOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bOptLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(bOptLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(bOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bOptLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bOptLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        bOptLayout.setVerticalGroup(
            bOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bOptLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(bOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(bOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        body.addTab("tab1", bOpt);

        bCompte.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel7.setText("Consulter mes comptes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("N° Compte:");

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setText("Consulter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        resultat.setBackground(new java.awt.Color(0, 51, 153));
        resultat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Résultat de la recherche");

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("N° Compte :");

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Solde :");

        r_solde.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        r_solde.setForeground(new java.awt.Color(255, 255, 255));
        r_solde.setText("5900$");

        r_compte.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        r_compte.setForeground(new java.awt.Color(255, 255, 255));
        r_compte.setText("CPT00");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Type de compte :");

        r_type.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        r_type.setForeground(new java.awt.Color(255, 255, 255));
        r_type.setText("Compte hypothecaire");

        javax.swing.GroupLayout resultatLayout = new javax.swing.GroupLayout(resultat);
        resultat.setLayout(resultatLayout);
        resultatLayout.setHorizontalGroup(
            resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultatLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(resultatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultatLayout.createSequentialGroup()
                        .addGroup(resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(r_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_solde, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultatLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r_type, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        resultatLayout.setVerticalGroup(
            resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultatLayout.createSequentialGroup()
                .addGroup(resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(r_compte))
                .addGap(18, 18, 18)
                .addGroup(resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_solde)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_type)
                    .addComponent(jLabel11))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bCompteLayout = new javax.swing.GroupLayout(bCompte);
        bCompte.setLayout(bCompteLayout);
        bCompteLayout.setHorizontalGroup(
            bCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bCompteLayout.createSequentialGroup()
                .addGroup(bCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bCompteLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bCompteLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(bCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bCompteLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numCpt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93)
                        .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        bCompteLayout.setVerticalGroup(
            bCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bCompteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(56, 56, 56)
                .addGroup(bCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bCompteLayout.createSequentialGroup()
                        .addGroup(bCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numCpt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        body.addTab("tab2", bCompte);

        bProfile.setBackground(new java.awt.Color(255, 255, 255));
        bProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("MON PROFIL");
        bProfile.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        body.addTab("tab3", bProfile);

        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 770, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            // TODO add your handling code here:
            new Main().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void sOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sOptMouseClicked
        // TODO add your handling code here:
        setActive(sOpt, 0);
        removeActive(sCompte);
        removeActive(sProfile);
    }//GEN-LAST:event_sOptMouseClicked

    private void sCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sCompteMouseClicked
        // TODO add your handling code here:
        setActive(sCompte, 1);
        removeActive(sOpt);
        removeActive(sProfile);
    }//GEN-LAST:event_sCompteMouseClicked

    private void sProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sProfileMouseClicked
        // TODO add your handling code here:
        setActive(sProfile, 2);
        removeActive(sCompte);
        removeActive(sOpt);
    }//GEN-LAST:event_sProfileMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFrame form;
        try {
            form = new FormTransfert(client);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setResizable(false);
            form.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame form;
        try {
            form = new FormRetrait(client);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setResizable(false);
            form.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        chargerTableOperation();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame form;
        try {
            form = new FormDepot(client);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setResizable(false);
            form.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        var code= numCpt.getSelectedItem();
        
        
        if(code== null){           
            JOptionPane.showMessageDialog(null, "Vous n'avait pas de compte pour le moment", "Recherche", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                ResultSet rs = db.getCompteByNumCpt(code.toString());
                if(rs.next()){
                    r_compte.setText(rs.getString("numCpt"));
                    r_solde.setText(rs.getFloat("solde")+" $");
                    r_type.setText(rs.getString("type"));
                   
                }
                resultat.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        resultat.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame form;
        try {
            form = new FormPaiementFacture(client);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setResizable(false);
            form.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClientDashboard().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bCompte;
    private javax.swing.JPanel bOpt;
    private javax.swing.JPanel bProfile;
    private javax.swing.JTabbedPane body;
    private javax.swing.JLabel client_name;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginDate;
    private javax.swing.JComboBox<String> numCpt;
    private javax.swing.JLabel r_compte;
    private javax.swing.JLabel r_solde;
    private javax.swing.JLabel r_type;
    private javax.swing.JPanel resultat;
    private javax.swing.JLabel sCompte;
    private javax.swing.JLabel sOpt;
    private javax.swing.JLabel sProfile;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel subHeader;
    private javax.swing.JLabel subHeaderTitle;
    private javax.swing.JTable tabOperation;
    // End of variables declaration//GEN-END:variables
}
